name = "github-cdn-worker"
main = "src/index.js"
compatibility_date = "2023-10-16"

# For Cloudflare Pages deployment
[site]
bucket = "./public"

# This is what Pages looks for
pages_build_output_dir = "public"

[vars]
# Define public variables here (do NOT include secrets here)
# These will be included in your published worker

# [secrets]
# GITHUB_TOKEN
# The GITHUB_TOKEN secret should be set using the Cloudflare Dashboard or CLI
# Do not include the actual token in this file